package com.fatec.teste;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
public class CT04ConsultaCEPcomLogradouroInvalido {
private WebDriver driver;
private Map<String, Object> vars;
JavascriptExecutor js;
@Before
public void setUp() {
System.setProperty("webdriver.chrome.driver", "browserDriver/chromedriver.exe");
driver = new ChromeDriver();
js = (JavascriptExecutor) driver;
vars = new HashMap<String, Object>();
}
@After
public void tearDown() {
driver.quit();
}
@Test
public void CT04ConsultaComSucesso() {
	driver.get("http://www.buscacep.correios.com.br/sistemas/buscacep/buscaCep.cfm");
    driver.manage().window().setSize(new Dimension(1936, 1066));
    driver.findElement(By.name("UF")).click();
    {
      WebElement dropdown = driver.findElement(By.name("UF"));
      dropdown.findElement(By.xpath("//option[. = 'SP']")).click();
    }
    driver.findElement(By.name("UF")).click();
    driver.findElement(By.name("Localidade")).click();
    driver.findElement(By.name("Localidade")).sendKeys("Sao Bernardo do Campo");
    driver.findElement(By.name("Tipo")).click();
    {
      WebElement dropdown = driver.findElement(By.name("Tipo"));
      dropdown.findElement(By.xpath("//option[. = 'Col√¥nia']")).click();
    }
    driver.findElement(By.name("Tipo")).click();
    driver.findElement(By.name("Logradouro")).click();
    driver.findElement(By.name("Logradouro")).sendKeys("@44-_*");
    driver.findElement(By.name("Numero")).click();
    driver.findElement(By.name("Numero")).sendKeys("366");
    driver.findElement(By.cssSelector(".btn2")).click();
    espera();
    assertThat(driver.findElement(By.cssSelector("p")).getText(), is("LOGRADOURO N√O ENCONTRADO."));
  }

public void espera() {
try {
Thread.sleep(1000);
} catch (InterruptedException e) {
e.printStackTrace();
}
}
}